app:
    resource: "@AppBundle/Controller/"
    type:     annotation
api:
    prefix:   /api
    resource: "@ApiBundle/Resources/config/routing.yml"
    type:     rest

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

api_login_check:
    path: /api/login_check