<?php

namespace AppBundle\Repository;

/**
 * AttachmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachmentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserAttachment($id){
        $q = $this->createQueryBuilder('a')
            ->leftJoin('a.users', 'u')
            ->select('a')
            ->where('u.id = :id')->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();

        return $q;
    }
}
