<?php

namespace AppBundle\Repository;

/**
 * ChecklistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChecklistRepository extends \Doctrine\ORM\EntityRepository
{
    public function countChecklistUnfinishedItems ($project){
        $q = $this->createQueryBuilder('checklists')
            ->leftJoin('checklists.items', 'items')
            ->leftJoin('checklists.project', 'project')
            ->select('count(items) as unfinished_items')
            ->where('project.hash = :hash')->setParameter('hash', $project)
            ->andWhere('items.finished = false')
            ->andWhere('items.inProgress = false')
            ->getQuery()
            ->getArrayResult();

        return $q[0];
    }

    public function ChecklistItems ($project_hash){
        $q = $this->createQueryBuilder('checklists')
            ->leftJoin('checklists.items', 'items')
            ->leftJoin('checklists.project', 'project')
            ->select('checklists, items, project as projects')
            ->where('project.hash = :hash')->setParameter('hash', $project_hash)
            ->getQuery()
            ->getArrayResult();

        return $q;
    }
}
