<?php

namespace AppBundle\Repository;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupsRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTeamMember($hash){
        $q = $this->createQueryBuilder('groups')
            ->leftJoin('groups.projects', 'p')
            ->leftJoin('groups.users', 'u')
            ->select('groups, u As users')
            ->where('p.hash = :hash')->setParameter('hash', $hash)
            ->getQuery()
            ->getOneOrNullResult();
        
        return $q;
    }

    public function getTeam($id){
        $q = $this->createQueryBuilder('groups')
            ->select('groups')
            ->where('groups.id = :id')->setParameter('id', $id)
            ->getQuery()
            ->getOneOrNullResult();
        
        return $q;
    }
    public function getTeamMemberAndPomodoroCount($hash){
          $q = $this->createQueryBuilder('groups')
            ->leftJoin('groups.projects', 'p')
            ->leftJoin('groups.users', 'u')
            ->leftJoin('u.pomodoros', 'pomo')
            ->select('groups, u As users, pomo')
            ->where('p.hash = :hash')->setParameter('hash', $hash)
            ->getQuery()
            ->getArrayResult();
        
        return $q;
    }
}
