<?php

namespace AppBundle\Repository;

/**
 * IssueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueRepository extends \Doctrine\ORM\EntityRepository
{
    public function countIssues($project){
        $q = $this->createQueryBuilder('issue')
            ->leftJoin('issue.project', 'project')
            ->select('Count(issue) As total_issues')
            ->where('project.hash = :hash')->setParameter('hash', $project)
            ->getQuery()
            ->getArrayResult();
        return $q[0];
    }

    public function getProjectIssues($hash){
        $q = $this->createQueryBuilder('issue')
            ->leftJoin('issue.project', 'p')
            ->select('issue')
            ->where('p.hash = :hash')->setParameter('hash', $hash)
            ->getQuery()
            ->getArrayResult();
        
        return $q;
    }

    public function getIssueByHash($hash){
        $q = $this->createQueryBuilder('issue')
            ->leftJoin('issue.project', 'p')
            ->select('issue.id, issue.title, issue.description, issue.estimatePomodoros As pomodoro, issue.urgent, p.title As project_title')
            ->where('issue.hash = :hash')->setParameter('hash', $hash)
            ->getQuery()
            ->getOneOrNullResult();
        
        return $q;
    }

     public function getIssue($hash){
        $q = $this->createQueryBuilder('issue')
            ->select('issue')
            ->where('issue.hash = :hash')->setParameter('hash', $hash)
            ->getQuery()
            ->getOneOrNullResult();
        
        return $q;
    }
}
