<?php

namespace AppBundle\Repository;

/**
 * PauseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PauseRepository extends \Doctrine\ORM\EntityRepository
{
}
