<?php

namespace AppBundle\Repository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends \Doctrine\ORM\EntityRepository
{
   public function getProjectTasks($hash){
        $q = $this->createQueryBuilder('task')
            ->leftJoin('task.project', 'p')
            ->select('task')
            ->where('p.hash = :hash')->setParameter('hash', $hash)
            ->getQuery()
            ->getArrayResult();
        return $q;
   }

    public function getTask($hash){
        $q = $this->createQueryBuilder('task')
            ->select('task')
            ->where('task.hash = :hash')->setParameter('hash', $hash)
            ->getQuery()
            ->getOneOrNullResult();
        return $q;
    }
   
    public function getUserTasks($username){
        $q = $this->createQueryBuilder('task')
            ->leftJoin('task.user', 'u')
            ->select('task')
            ->where('u.username = :username')->setParameter('username', $username)
            ->getQuery()
            ->getArrayResult();
        return $q;
   }
   

}
