# FOS Rest Bundle
# Further reading: http://symfony.com/doc/current/bundles/FOSRestBundle/configuration-reference.html
fos_rest:
    param_fetcher_listener: true
#    body_listener: true
#    format_listener:
#        enabled: true # Use of '_format' parameter.
    view:
        view_response_listener: "force"
#        force_redirects:
#            html: false
#        formats:
#            json:  true
#            jsonp: false
#            xml:   true
        templating_formats:
            html: true
        jsonp_handler: ~
    exception:
        codes:
            "Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException": 404
            "Doctrine\\ORM\\OptimisticLockException": HTTP_CONFLICT
    routing_loader:
        default_format: json # Value for '_format' parameter if none is specified.
        include_format: true

# Nelmio Api Doc Bundle
# Further reading: http://symfony.com/doc/current/bundles/NelmioApiDocBundle/configuration-reference.html
nelmio_api_doc:
    name: "API documentation"
    sandbox:
        accept_type: application/json
        body_format:
            default_format: json

# Nelmio Cors Bundle
# Further reading: https://github.com/nelmio/NelmioCorsBundle
nelmio_cors:
    paths:
        "^/api/":
            allow_origin: "*"
            allow_headers: ["X-Custom-Auth", "Authorization", "Content-Type"]
            allow_methods: ["POST", "PUT", "GET", "DELETE", "OPTIONS"]
            expose_headers: ["Location"]
            max_age: 3600

